const GLOBAL_PREFIX = "GLOBAL";
export const GLOBAL_ACTION_TYPE = {
  SHOW_LOADING: `${GLOBAL_PREFIX}/SHOW_LOADING`,
  HIDE_LOADING: `${GLOBAL_PREFIX}/HIDE_LOADING`,
  CHANGE_LOCALE: `${GLOBAL_PREFIX}/CHANGE_LOCALE`,

  UPDATE_LAYOUT: `${GLOBAL_PREFIX}/UPDATE_LAYOUT`,

  ADD_NOTIFICATION: `${GLOBAL_PREFIX}/ADD_NOTIFICATION`,
  REMOVE_NOTIFICATION: `${GLOBAL_PREFIX}/REMOVE_NOTIFICATION`,

  UPLOAD_IMAGE_REQUEST: `${GLOBAL_PREFIX}/UPLOAD_IMAGE_REQUEST`,
  UPLOAD_IMAGE_SUCCEED: `${GLOBAL_PREFIX}/UPLOAD_IMAGE_SUCCEED`,
  UPLOAD_IMAGE_FAIL: `${GLOBAL_PREFIX}/UPLOAD_IMAGE_FAIL`,

  DATETIME_FORMAT: `${GLOBAL_PREFIX}/DATETIME_FORMAT`,
}

export const GENERIC_DATA_MANAGEMENT_PREFIX = "GENERIC"
export const GENERIC_DATA_MANAGEMENT_TYPE = {
  GET_LIST_REQUEST: `${GENERIC_DATA_MANAGEMENT_PREFIX}/GET_LIST_REQUEST`,
  GET_LIST_SUCCEED: `${GENERIC_DATA_MANAGEMENT_PREFIX}/GET_LIST_SUCCEED`,
  GET_LIST_FAIL: `${GENERIC_DATA_MANAGEMENT_PREFIX}/GET_LIST_FAIL`,

  ADD_REQUEST: `${GENERIC_DATA_MANAGEMENT_PREFIX}/ADD_REQUEST`,
  ADD_SUCCEED: `${GENERIC_DATA_MANAGEMENT_PREFIX}/ADD_SUCCEED`,
  ADD_FAIL: `${GENERIC_DATA_MANAGEMENT_PREFIX}/ADD_FAIL`,

  DELETE_REQUEST: `${GENERIC_DATA_MANAGEMENT_PREFIX}/DELETE_REQUEST`,
  DELETE_SUCCEED: `${GENERIC_DATA_MANAGEMENT_PREFIX}/DELETE_SUCCEED`,
  DELETE_FAIL: `${GENERIC_DATA_MANAGEMENT_PREFIX}/DELETE_FAIL`,

  UPDATE_ROLE_REQUEST: `${GENERIC_DATA_MANAGEMENT_PREFIX}/UPDATE_ROLE_REQUEST`,
  UPDATE_ROLE_SUCCEED: `${GENERIC_DATA_MANAGEMENT_PREFIX}/UPDATE_ROLE_SUCCEED`,
  UPDATE_ROLE_FAIL: `${GENERIC_DATA_MANAGEMENT_PREFIX}/UPDATE_ROLE_FAIL`,

  UPDATE_PAGING_SETTING: `${GENERIC_DATA_MANAGEMENT_PREFIX}/UPDATE_PAGING_SETTING`,
}

export const USER_PREFIX = "USER"
export const USER_TYPE = {
  GET_CURRENT_USER_REQUEST:`${USER_PREFIX}/GET_CURRENT_USER_REQUEST`,
  GET_CURRENT_USER_SUCCEED:`${USER_PREFIX}/GET_CURRENT_USER_SUCCEED`,
  GET_CURRENT_USER_FAIL:`${USER_PREFIX}/GET_CURRENT_USER_FAIL`,

  GET_LIST_REQUEST: `${USER_PREFIX}/GET_LIST_REQUEST`,
  GET_LIST_SUCCEED: `${USER_PREFIX}/GET_LIST_SUCCEED`,
  GET_LIST_FAIL: `${USER_PREFIX}/GET_LIST_FAIL`,

  UPDATE_ROLE_REQUEST: `${USER_PREFIX}/UPDATE_ROLE_REQUEST`,
  UPDATE_ROLE_SUCCEED: `${USER_PREFIX}/UPDATE_ROLE_SUCCEED`,
  UPDATE_ROLE_FAIL: `${USER_PREFIX}/UPDATE_ROLE_FAIL`,

  UPDATE_REQUEST: `${USER_PREFIX}/UPDATE_REQUEST`,
  UPDATE_SUCCEED: `${USER_PREFIX}/UPDATE_SUCCEED`,
  UPDATE_FAIL: `${USER_PREFIX}/UPDATE_FAIL`,

  UPDATE_PAGING_SETTING: `${USER_PREFIX}/UPDATE_PAGING_SETTING`,

}

export const ROLE_PREFIX = "ROLE"
export const ROLE_TYPE = {
  GET_LIST_REQUEST: `${ROLE_PREFIX}/GET_LIST_REQUEST`,
  GET_LIST_SUCCEED: `${ROLE_PREFIX}/GET_LIST_SUCCEED`,
  GET_LIST_FAIL: `${ROLE_PREFIX}/GET_LIST_FAIL`,

  ADD_REQUEST: `${ROLE_PREFIX}/ADD_REQUEST`,
  ADD_SUCCEED: `${ROLE_PREFIX}/ADD_SUCCEED`,
  ADD_FAIL: `${ROLE_PREFIX}/ADD_FAIL`,

  DELETE_REQUEST: `${ROLE_PREFIX}/DELETE_REQUEST`,
  DELETE_SUCCEED: `${ROLE_PREFIX}/DELETE_SUCCEED`,
  DELETE_FAIL: `${ROLE_PREFIX}/DELETE_FAIL`,

  UPDATE_ROLE_REQUEST: `${ROLE_PREFIX}/UPDATE_ROLE_REQUEST`,
  UPDATE_ROLE_SUCCEED: `${ROLE_PREFIX}/UPDATE_ROLE_SUCCEED`,
  UPDATE_ROLE_FAIL: `${ROLE_PREFIX}/UPDATE_ROLE_FAIL`,

  UPDATE_PAGING_SETTING: `${ROLE_PREFIX}/UPDATE_PAGING_SETTING`,
}

export const EVENT_PREFIX = "EVENT"
export const EVENT_TYPE = {
  GET_LIST_REQUEST: `${EVENT_PREFIX}/GET_LIST_REQUEST`,
  GET_LIST_SUCCEED: `${EVENT_PREFIX}/GET_LIST_SUCCEED`,
  GET_LIST_FAIL: `${EVENT_PREFIX}/GET_LIST_FAIL`,

  ASSIGN_CHOICE_REQUEST: `${EVENT_PREFIX}/ASSIGN_CHOICE_REQUEST`,
  ASSIGN_CHOICE_SUCCEED: `${EVENT_PREFIX}/ASSIGN_CHOICE_REQUEST`,
  ASSIGN_CHOICE_FAIL: `${EVENT_PREFIX}/ASSIGN_CHOICE_REQUEST`,

  SET_ACTIVE_CHOICE: `${EVENT_PREFIX}/SET_ACTIVE_CHOICE`,

  UPDATE_PAGING_SETTING: `${EVENT_PREFIX}/UPDATE_PAGING_SETTING`,
}