export const SET_HEADER_TEXT = 'SET_HEADER_TEXT'
export const SHOW_LOADING = 'SHOW_LOADING'
export const HIDE_LOADING = 'HIDE_LOADING'
export const CHANGE_LOCATE_SUCCESS = 'CHANGE_LOCATE_SUCCESS'

export const LOCATION_PREFIX = "LOCATION";
export const LOCATION_TYPE = {
    GET_LIST_REQUEST: `${LOCATION_PREFIX}/GET_LIST_REQUEST`,
    GET_LIST_SUCCEED: `${LOCATION_PREFIX}/GET_LIST_SUCCEED`,
    GET_LIST_FAIL: `${LOCATION_PREFIX}/GET_LIST_FAIL`,
}

