export const GET_MY_ACTIVITIES_REQUEST = 'GET_MY_ACTIVITIES_REQUEST'
export const GET_MY_ACTIVITIES_SUCCESS = 'GET_MY_ACTIVITIES_SUCCESS'
export const GET_MY_ACTIVITIES_FAILURE = 'GET_MY_ACTIVITIES_FAILURE'

export const GET_PAST_DUE_ACTIVITIES_REQUEST = 'GET_PAST_DUE_ACTIVITIES_REQUEST'
export const GET_PAST_DUE_ACTIVITIES_SUCCESS = 'GET_PAST_DUE_ACTIVITIES_SUCCESS'
export const GET_PAST_DUE_ACTIVITIES_FAILURE = 'GET_PAST_DUE_ACTIVITIES_FAILURE'

export const GET_PAST_DUE_ACTIVITIES_COUNT_SUCCESS = 'GET_PAST_DUE_ACTIVITIES_COUNT_SUCCESS'

export const TOGGLE_ACTIVITY_STATUS_REQUEST = 'TOGGLE_ACTIVITY_STATUS_REQUEST'
export const TOGGLE_ACTIVITY_STATUS_SUCCESS = 'TOGGLE_ACTIVITY_STATUS_SUCCESS'
export const TOGGLE_ACTIVITY_STATUS_FAILURE = 'TOGGLE_ACTIVITY_STATUS_FAILURE'

export const LOG_SYMPTOMS_SUCCESS = 'LOG_SYMPTOMS_SUCCESS'

export const GET_MY_APPOINTMENTS_REQUEST = 'GET_MY_APPOINTMENTS_REQUEST'
export const GET_MY_APPOINTMENTS_SUCCESS = 'GET_MY_APPOINTMENTS_SUCCESS'
export const GET_MY_APPOINTMENTS_FAILURE = 'GET_MY_APPOINTMENTS_FAILURE'
export const CLEAN_MY_APPOINTMENTS = 'CLEAN_MY_APPOINTMENTS'


export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST'
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS'
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE'

export const CREATE_CLIENT_APPOINTMENT_REQUEST = 'CREATE_APPOINTMENT_REQUEST'
export const CREATE_CLIENT_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS'
export const CREATE_CLIENT_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE'

export const GET_MY_DOCUMENTS_REQUEST = 'GET_MY_DOCUMENTS_REQUEST'
export const GET_MY_DOCUMENTS_SUCCESS = 'GET_MY_DOCUMENTS_SUCCESS'
export const GET_MY_DOCUMENTS_FAILURE = 'GET_MY_DOCUMENTS_FAILURE'

export const CLEAR_MY_DOCUMENTS_STATE = 'CLEAR_MY_DOCUMENTS_STATE'

export const UPLOAD_DOCUMENTS_REQUEST = 'UPLOAD_DOCUMENTS_REQUEST'
export const UPLOAD_DOCUMENTS_SUCCESS = 'UPLOAD_DOCUMENTS_SUCCESS'
export const UPLOAD_DOCUMENTS_FAILURE = 'UPLOAD_DOCUMENTS_FAILURE'

export const DELETE_MY_DOCUMENTS_REQUEST = 'DELETE_MY_DOCUMENTS_REQUEST'
export const DELETE_MY_DOCUMENTS_SUCCESS = 'DELETE_MY_DOCUMENTS_SUCCESS'
export const DELETE_MY_DOCUMENTS_FAILURE = 'DELETE_MY_DOCUMENTS_FAILURE'

export const INITIALIZE_COGNITIVE_BASELINE_REQUEST = 'INITIALIZE_COGNITIVE_BASELINE_REQUEST'
export const INITIALIZE_COGNITIVE_BASELINE_SUCCESS = 'INITIALIZE_COGNITIVE_BASELINE_SUCCESS'
export const INITIALIZE_COGNITIVE_BASELINE_FAILURE = 'INITIALIZE_COGNITIVE_BASELINE_FAILURE'

export const CREATE_PAYMENT_INTENT_REQUEST = 'CREATE_PAYMENT_INTENT_REQUEST'
export const CREATE_PAYMENT_INTENT_SUCCESS = 'CREATE_PAYMENT_INTENT_SUCCESS'
export const CREATE_PAYMENT_INTENT_FAILURE = 'CREATE_PAYMENT_INTENT_FAILURE'

export const APPLY_COUPON_REQUEST = 'APPLY_COUPON_REQUEST'
export const APPLY_COUPON_SUCCESS = 'APPLY_COUPON_SUCCESS'
export const APPLY_COUPON_FAILURE = 'APPLY_COUPON_FAILURE'

export const GET_LIST_COGNITIVE_BASELINE_REQUEST = 'GET_LIST_COGNITIVE_BASELINE_REQUEST'
export const GET_LIST_COGNITIVE_BASELINE_SUCCESS = 'GET_LIST_COGNITIVE_BASELINE_SUCCESS'
export const GET_LIST_COGNITIVE_BASELINE_FAILURE = 'GET_LIST_COGNITIVE_BASELINE_FAILURE'

export const UPDATE_AVATAR_REQUEST = 'UPDATE_AVATAR_REQUEST'
export const UPDATE_AVATAR_SUCCESS = 'UPDATE_AVATAR_SUCCESS'
export const UPDATE_AVATAR_FAILURE = 'UPDATE_AVATAR_FAILURE'

export const UPDATE_PROFILE_DETAILS_REQUEST = 'UPDATE_PROFILE_DETAILS_REQUEST'
export const UPDATE_PROFILE_DETAILS_SUCCESS = 'UPDATE_PROFILE_DETAILS_SUCCESS'
export const UPDATE_PROFILE_DETAILS_FAILURE = 'UPDATE_PROFILE_DETAILS_FAILURE'
